fixed issue with installing remi repo and added missing PHP extensions
stackery/php-lambda-layer pull request #39
Opened 2019-05-28 22:53 UTC by titomiguelcosta

This PR, fixes issue #38 

In the end, it was a small fix. When building the php73.zip there were errors in installing remi repo, and it all came down to the order we installed epel and remi, reverting those instructions fixed the problem.

In term of adding the missing extensions required by Symfony 4, I only had to add php-xml and php-process to the list of php packages to be installed.

I tested and deployed the generated layer. phpinfo can be seen [here](https://3crp2q2q4l.execute-api.ap-southeast-2.amazonaws.com/Prod/home) (this page will be deleted once we merge this PR).

**Side note:** I did not explore, but I wonder why do we need to install httpd as part of building the image?! In my case, I'm using API Gateway to handle the requests and fire the lambda. I might be missing something but I do not think we need apache.

2019-05-28 22:55 UTC, titomiguelcosta commented
To test my PR, just change to my branch and run `$ make php73.zip`
Done on a Linux Mint 19.1 box with docker 18.09.6, build 481bc77

2019-05-31 18:39 UTC, txase requested changes
This looks good to me! Can you also update the readme with the additional extensions this provides in the runtime layer?

:pray:

2019-05-31 21:32 UTC, titomiguelcosta commented
> This looks good to me! Can you also update the readme with the additional extensions this provides in the runtime layer?

@txase sure thing, done. copied the output of the command and put on the README sorted alphabetically

2019-05-31 21:33 UTC, txase approved these changes

2019-05-31 21:33 UTC, merged

2019-05-31 21:34 UTC, txase commented
Thanks!

I’ll look to update the layer in AWS early next week!

2021-08-01 16:38 UTC, ronald2wing commented
xmlreader still missing